spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 
    username: 
    password: 
  data:
    redis:
      host: 
      port: 
      password: 

mybatis:
  configuration:
    map-underscore-to-camel-case: true  #开启属性的驼峰命名和下划线分割命名的相互映射
